
#macro FIRSTROOM rTitle
#macro WINDOWWIDTH 990
#macro WINDOWHEIGHT 540
#macro CAMERASCALE 2
#macro GAMEWIDTH WINDOWWIDTH/CAMERASCALE
#macro GAMEHEIGHT WINDOWHEIGHT/CAMERASCALE
#macro SEALEVEL 100
#macro GROUNDPOS room_height-32

#macro MAINROOM rMain
#macro TITLEROOM rTitle

enum DRAWEVENT{
	DRAWBEGIN,
	DRAW,
	DRAWEND,
	DRAWGUIBEGIN,
	DRAWGUI,
	DRAWGUIEND,
}

