
#macro FIRSTROOM rTitle
#macro WINDOWWIDTH 990
#macro WINDOWHEIGHT 540
#macro CAMERASCALE 2
#macro GAMEWIDTH WINDOWWIDTH/CAMERASCALE
#macro GAMEHEIGHT WINDOWHEIGHT/CAMERASCALE
#macro SEALEVEL 100
#macro GROUNDPOS (room_height-32)




#macro MAINROOM rMain
#macro TITLEROOM rTitle

//アイテム
#macro MAXSPEEDLEVEL 10
#macro MAXINFINITEJUMPTIME 600
#macro SPEEDUPRATIOPERLEVEL 1.15
#macro DECREASESPEEDLEVEL 3//ダメージを受けた時に減るスピードレベル
#macro THROUGHSPEEDUPCOUNTLIMIT 3//スピードアップアイテムをスルーできる回数 これを超えてスルーするとスピードが減る
#macro DECREASETEMPSPEEDTIME 180//仮スピードの減少時間
#macro TEMPSPEEDMAX 20//仮スピード値上限
#macro ITEMGETSCOREBASE 20000//アイテム取得ボーナススコア
#macro ITEMGETSCORECOLOR $34df45//アイテム取得時のスコアの色

//バランス
#macro MAXLEVEL 50
#macro SCORERATIOPERLEVEL 0.1
#macro GROUNDENABLE false
#macro DAMAGEDTIMEBASE 120


//ランダムイベント



enum DRAWEVENT{
	DRAWBEGIN,
	DRAW,
	DRAWEND,
	DRAWGUIBEGIN,
	DRAWGUI,
	DRAWGUIEND,
}

